# Generated by Django 6.0.3 on 2026-04-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigMensageiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_api', models.CharField(default='https://mensageiro.exata.net/api/messages/sendText/', help_text='URL completa do endpoint sendText', max_length=255)),
                ('instancia', models.CharField(help_text='Nome da instância no mensageiro', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuração do Mensageiro',
                'verbose_name_plural': 'Configuração do Mensageiro',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero', models.CharField(help_text='Somente dígitos, com DDI. Ex: 5527999998888', max_length=30)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['nome'],
            },
        ),
    ]
