# Generated by Django 4.2.28 on 2026-02-19 15:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_retorno', models.DateTimeField(blank=True, null=True)),
                ('qtd_saida', models.PositiveIntegerField(help_text='Quantidade de entregas que o motoboy saiu')),
                ('status', models.CharField(choices=[('em_rota', 'Em Rota'), ('retornando', 'Retornando'), ('finalizado', 'Finalizado')], default='em_rota', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Despacho',
                'verbose_name_plural': 'Despachos',
                'ordering': ['-data_saida'],
            },
        ),
        migrations.CreateModel(
            name='Motoboy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('valor_fixo', models.DecimalField(decimal_places=2, default=0, help_text='Valor fixo por turno/dia', max_digits=8)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Motoboy',
                'verbose_name_plural': 'Motoboys',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Centro, Bairro Norte, Rota 1', max_length=100)),
                ('taxa_entrega', models.DecimalField(decimal_places=2, default=0, help_text='Taxa cobrada por entrega nesta rota', max_digits=8)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('online', 'Pago Online')], max_length=20)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='Valor cobrado em dinheiro (só para pagamento em dinheiro)', max_digits=10, null=True)),
                ('cliente', models.CharField(blank=True, max_length=150)),
                ('observacoes', models.CharField(blank=True, max_length=255)),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='entregas.despacho')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='entregas.rota')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='despacho',
            name='motoboy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='entregas.motoboy'),
        ),
    ]
