# Generated by Django 4.2.28 on 2026-02-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0002_remove_entrega_cliente_alter_entrega_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('online', 'Pago Online'), ('pix', 'Pix')], max_length=20),
        ),
    ]
