# Generated by Django 4.2.29 on 2026-04-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0005_pagamento_parcial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentoentrega',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('online', 'Pago Online'), ('pix', 'Pix'), ('yooga', 'Yooga')], max_length=20),
        ),
        migrations.AlterField(
            model_name='retirada',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('online', 'Pago Online'), ('pix', 'Pix'), ('yooga', 'Yooga')], max_length=20),
        ),
    ]
