# Generated by Django 4.2.28 on 2026-02-19 14:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('responsavel', models.CharField(default='Operador', max_length=100)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado')], default='aberto', max_length=10)),
                ('observacoes', models.TextField(blank=True)),
                ('total_abertura', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_fechamento', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixas',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='ContaCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('abertura', 'Abertura'), ('fechamento', 'Fechamento')], max_length=15)),
                ('denominacao', models.CharField(choices=[('nota_200', 'Nota R$ 200'), ('nota_100', 'Nota R$ 100'), ('nota_50', 'Nota R$ 50'), ('nota_20', 'Nota R$ 20'), ('nota_10', 'Nota R$ 10'), ('nota_5', 'Nota R$ 5'), ('nota_2', 'Nota R$ 2'), ('moeda_100', 'Moeda R$ 1,00'), ('moeda_50', 'Moeda R$ 0,50'), ('moeda_25', 'Moeda R$ 0,25'), ('moeda_10', 'Moeda R$ 0,10'), ('moeda_5', 'Moeda R$ 0,05'), ('moeda_1', 'Moeda R$ 0,01')], max_length=20)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='caixa.caixa')),
            ],
        ),
    ]
