# Generated by Django 4.2.29 on 2026-04-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacaixa',
            name='denominacao',
            field=models.CharField(choices=[('nota_200', 'Nota R$ 200'), ('nota_100', 'Nota R$ 100'), ('nota_50', 'Nota R$ 50'), ('nota_20', 'Nota R$ 20'), ('nota_10', 'Nota R$ 10'), ('nota_5', 'Nota R$ 5'), ('nota_2', 'Nota R$ 2'), ('moeda_100', 'Moeda R$ 1,00'), ('moeda_50', 'Moeda R$ 0,50'), ('moeda_25', 'Moeda R$ 0,25'), ('moeda_10', 'Moeda R$ 0,10'), ('moeda_5', 'Moeda R$ 0,05')], max_length=20),
        ),
    ]
